import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'

describe('ThreadSideConversation wiring', () => {
  it('minimizes without ending and keeps desktop drag and accessible resize wiring', async () => {
    const source = await readFile(new URL('./ThreadSideConversation.vue', import.meta.url), 'utf8')
    const appSource = await readFile(new URL('../../App.vue', import.meta.url), 'utf8')

    expect(source).toContain('sendWithEnter?: boolean')
    expect(source).toContain('visible: boolean')
    expect(source).toContain('draft: string')
    expect(source).toContain('@keydown="onInputKeydown"')
    expect(source).toContain('@input="updateDraft"')
    expect(source).toContain('shouldSubmitComposer(event, props.sendWithEnter)')
    expect(source).toContain('minimize: []')
    expect(source).toContain('end: []')
    expect(source).toContain("'update:draft': [value: string]")
    expect(source).toContain("t('Minimize side conversation')")
    expect(source).toContain("t('End side conversation')")
    expect(source).toContain('v-show="visible"')
    expect(source).not.toContain(':disabled="isOpening"')
    expect(source).toContain("@click.self=\"emit('minimize')\"")
    expect(source).toContain("@click=\"emit('end')\"")
    expect(source).toContain("interrupt: []")
    expect(source).toContain('side-conversation-action--stop')
    expect(source).toContain('@pointerdown="onSideConversationHeaderPointerDown"')
    expect(source).toContain('@pointerdown="onSideConversationResizePointerDown"')
    expect(source).toContain('aria-orientation="vertical"')
    expect(source).toContain(':aria-valuemin="sideConversationWindowWidthRange.minimum"')
    expect(source).toContain(':aria-valuemax="sideConversationWindowWidthRange.maximum"')
    expect(source).toContain(':aria-valuenow="sideConversationWindow.width"')
    expect(source).toContain('tabindex="0"')
    expect(source).toContain('@keydown="onSideConversationResizeKeydown"')
    const resizeKeydownBody = source.match(/function onSideConversationResizeKeydown\(event: KeyboardEvent\): void \{([\s\S]*?)\n\}/u)?.[1] ?? ''
    expect(resizeKeydownBody).toContain("event.key === 'ArrowLeft'")
    expect(resizeKeydownBody).toContain("event.key === 'ArrowRight'")
    expect(resizeKeydownBody).toContain("event.key === 'ArrowUp'")
    expect(resizeKeydownBody).toContain("event.key === 'ArrowDown'")
    expect(resizeKeydownBody).toContain('clampTerminalWindowRect')
    expect(source).toContain('clampTerminalWindowRect')
    expect(source).toContain("window.addEventListener('pointermove', onSideConversationWindowPointerMove)")
    expect(source).toContain("window.removeEventListener('pointermove', onSideConversationWindowPointerMove)")
    expect(source).not.toContain('side-conversation-draft.v2.')
    expect(appSource).toContain(':send-with-enter="sendWithEnter"')
    expect(appSource).toContain(':side-conversation-open="isSideConversationVisible"')
    expect(appSource).toContain(':visible="isSideConversationVisible"')
    expect(appSource).toContain(':draft="sideConversationDraft"')
    expect(appSource).toContain('@minimize="hideSideConversation"')
    expect(appSource).toContain('@end="endSideConversation"')
    expect(appSource).not.toContain('@close="endSideConversation"')
    expect(appSource).toContain('@update:draft="setSideConversationDraft"')
    expect(appSource).toContain('@interrupt="interruptSideConversationTurn"')
    expect(appSource).toContain(':cwd="composerCwd"')
    expect(appSource).not.toContain('sideConversationCwd')
    expect(appSource).toContain('discardSideConversationInBackground()')
    expect(appSource).toContain('let accountStateRequestEpoch = 0')
    expect(appSource).toContain('requestEpoch !== accountStateRequestEpoch')
  })
})
